apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ankit-lb004
  name: ankit-lb004
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ankit-app-ui  # here we put label of deployment 
  type: LoadBalancer
status:
  loadBalancer: {}
